### ISSUE TITLE
"need layout: true"

### ISSUE THREAD

**Issue by devabir93** [bambuser/bambuser-examplebroadcaster-android#1]
hello I am using your beautiful lib, but i getting strange behavior, the camera didn't preview unless after the app goes to on pause and on resume methods.
and when app fire on I notice a log "need layout: true" with not previewing camera, and after onPause and onResume I got "need layout: false" and it is previewing.

I am using the same code in the tutorial.

**Comment by JohanSchoring** [comment]
These log messages come from the SurfaceViewWithAutoAR component, which you can use if you want a UI component that handles its aspect ratio automatically.

As documented on https://bambuser.com/docs/reference/android-sdk-current/com/bambuser/broadcaster/Broadcaster.html#setCameraSurface-android.view.SurfaceView-

"If the SurfaceView is an instance of SurfaceViewWithAutoAR, the camera will set the proper aspect ratio to the surface view and will start when the changes have applied. Make sure that a SurfaceViewWithAutoAR can resize itself within the parent layout (use WRAP_CONTENT), otherwise the camera will not start."
