### ISSUE TITLE
omar nagah

### ISSUE THREAD

**Issue by OmarSakr** [bambuser/bambuser-examplebroadcaster-android#3]
it's npot working fine in api 24 the camera never revels to user to start broadcasting after 24 works like charm what do i need to do ?

**Comment by JohanSchoring** [comment]
The broadcaster SDK and this example app currently work on any API level from 16 up.

If the camera doesn't start, it may for example be that it's waiting for a SurfaceViewWithAutoAR to be resized to the proper aspect ratio. This can happen on some devices but not on others, as some start with different aspect ratios. As documented on https://bambuser.com/docs/reference/android-sdk-current/com/bambuser/broadcaster/Broadcaster.html#setCameraSurface-android.view.SurfaceView-

"Make sure that a SurfaceViewWithAutoAR can resize itself within the parent layout (use WRAP_CONTENT), otherwise the camera will not start."

If this doesn't work, please let us know if you are running this exact example or a modified version in your own app.
